server {
	listen 80;
	server_name _;
	root /usr/share/nginx/html;
	index index.html;
	gzip on;
	gzip_vary on;
	gzip_proxied any;
	gzip_comp_level 5;
	gzip_min_length 1024;
	gzip_types application/javascript text/javascript text/css;
	location ~* \.(?:js|mjs|css|map|webp|png|jpe?g|gif|svg|ico|woff2?|ogg|mp3|wav|webm)$ {
		try_files $uri =404;
	}
	location / {
		try_files $uri $uri/ /index.html;
	}
}
